# Generated by Django 6.0.1 on 2026-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Número de referencia de transferencia bancaria reportado por el cliente', max_length=50, null=True, verbose_name='Número de Referencia Bancaria'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Transferencia Bancaria')], max_length=20, verbose_name='Método de Pago'),
        ),
    ]
