# Generated by Django 6.0.1 on 2026-02-19 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_bank_reference_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Entre 6 y 12 dígitos numéricos del comprobante de transferencia', max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_bank_reference', message='La referencia bancaria debe contener solo dígitos y tener entre 6 y 12 caracteres.', regex='^\\d{6,12}$')], verbose_name='Número de Referencia Bancaria'),
        ),
    ]
