# Generated by Django 6.0.1 on 2026-02-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Clase')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Video')),
                ('imagen_portada', models.URLField(blank=True, max_length=500, null=True, verbose_name='Miniatura de Clase')),
                ('duracion_estimada', models.IntegerField(default=0, help_text='Duración en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='course_app.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
                'ordering': ['orden'],
            },
        ),
    ]
