# Generated by Django 6.0.1 on 2026-02-01 04:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Curso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen_portada', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen de Portada')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='PRINCIPIANTE', max_length=20, verbose_name='Nivel')),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración estimada en minutos', null=True, verbose_name='Duración Estimada (min)')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['profesor'], name='curso_profeso_99bda1_idx'), models.Index(fields=['publicado'], name='curso_publica_a15a54_idx'), models.Index(fields=['-fecha_creacion'], name='curso_fecha_c_aa1890_idx')],
            },
        ),
    ]
