# Generated by Django 6.0.1 on 2026-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_adjuntos',
            field=models.TextField(blank=True, default='[]', help_text='Lista de URLs de PDFs adjuntos en formato JSON', null=True, verbose_name='PDFs Adjuntos'),
        ),
    ]
