# Generated by Django 6.0.1 on 2026-02-01 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual'), ('LIFETIME', 'Vitalicio')], default='MONTHLY', max_length=20, verbose_name='Tipo de Plan')),
                ('duration_days', models.IntegerField(default=30, help_text='Duración del plan en días', verbose_name='Duración (días)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio original (para mostrar descuento)', max_digits=10, null=True, verbose_name='Precio Original')),
                ('features', models.JSONField(blank=True, default=list, help_text='Lista de características del plan', verbose_name='Características')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='Destacar como mejor opción', verbose_name='Destacado')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Plan de Membresía',
                'verbose_name_plural': 'Planes de Membresía',
                'db_table': 'membership_plan',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendiente de Pago')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renovación Automática')),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='membership.membershipplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Usuario',
                'verbose_name_plural': 'Membresías de Usuarios',
                'db_table': 'user_membership',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_member_user_id_d7976f_idx'), models.Index(fields=['end_date'], name='user_member_end_dat_df9c6c_idx')],
            },
        ),
    ]
